[package]
name = "triangle"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-lite.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true
winit.workspace = true
